### PR TITLE
add fastqtools and samtools bioinformatics apps

### PR DESCRIPTION
**Pull request by alaindomissy**

### CODE REVIEW

**Comment by vsoch** [comment]
okay, we have tests! Apologies that this wasn't triggering. Could you make a trivial change and we can start afresh? I was changing around the parallelism and I think we want to stick with 1x. I triggered the webhook manually but the settings for the 4x build seem to be stuck. Once we get tests up and working I'll test these out locally too - this is so great! :LD

**Comment by vsoch** [comment]
woohoo we have tests running! Here is a better description about what they are complaining about:

 - **url in filename** to guarantee that the apps provided in the repository have unique names, we go off of the folder hierarchy. So an app in `bioinforumatics/samtools` should have an app name of `bioinformatics-samtools`. That's this bit

```
**********************************************
bioinformatics/samtools:
Markdown must reflect folders above it. Found:
                             FILENAME: samtools.md
                             FOLDERS: bioinformatics
```

and then this last one is just a copy paste (and forget to rename) error, I've done this many times! (hence why I created a test:

```
**********************************************
bioinformatics/fastq-tools:
Name of section %applabels samtools must correspond with file name fastq-tools
```

**Comment by vsoch** [comment]
okay I'm building your apps!! This is fun :)

**Comment by vsoch** [comment]
samtools is a go! It looks like there is a bug in downloading the recipe - the ampersands change from & to amp, so samtools works (and fastq-tools not) hang tight so I can fix that, then I think your final recipe should be good.

**Comment by alaindomissy** [comment]
Thanks. I renamed fastq-tools to fastqtools everywhere.

**Comment by vsoch** [comment]
yeah this is a bug that I am fixing now - hadn't yet seen a special character in a recipe! About to test again!

**Comment by vsoch** [comment]
okay I'm about finishing up - one quick comment - when you add this to labels:

```
BUILD_DATE $(date -Ihours)
```
renders to
```
singularity inspect --app bioinformatics-samtools fastq.simg 
{
    "BUILD_DATE": "$(date -Ihours)",
    "MAINTAINER": "adomissy@ucsd.edu",
    "SINGULARITY_APP_SIZE": "5MB",
    "SINGULARITY_APP_NAME": "bioinformatics-samtools",
    "VERSION": "0.0.1",
    "WRAPPEDTOOL_VERSION_": "1.3.0"
}
```
since it's just a text file, it doesn't get parsed as a variable. The build date is added automatically to containers when they are built, so is it ok if I remove these from each of the recipes?

**Comment by alaindomissy** [comment]
Sure. Thanks!

**Comment by vsoch** [comment]
there were a few issues - the recipe included isn't actually necessary (but it's nice so I included it) - the markdown file has the "real" one that is used. That was different from the recipe (comments vs. not and missing dependencies) so I fixed it up. The other issue was not having an interpreter for the fastqtools script - so I called it with bash. Finally, I would suggest possibly a change that, given that run is done with an argument, just exec it (without the fastqtools script) to call the tool directly, so this would work:

```
singularity run --app bioinformatics-fastqtools fastq-grep
```
instead of printing out the text. You would only want the text if the user runs:

```
singularity run --app bioinformatics-fastqtools
```

because right now you are forcing them to do this in order to run an app:

```
singularity exec --app bioinformatics-fastqtools fastq-grep
```
which defeats the purpose a little bit, because they could exec without apps. But it's a tiny detail, and pretty trivial.

**Comment by vsoch** [comment]
I'm testing now - it looks like the executables aren't fully installed in the container. Could you test it out and file a PR to fix it up? It just means there was an issue copying them, etc.

**Comment by vsoch** [comment]
once it's working smoothly we can show the list your great work!

**Pull request merged**
