### PR TITLE
fastqtools usage only if no args - other small fixes

### PR DESCRIPTION
**Pull request by alaindomissy**

### CODE REVIEW

**Comment by vsoch** [comment]
woot! I will give a test when it's done with CI.

You know, it might be reasonable to require submissions to include the SingularityApp.<appname> file, just so 1) we can easily test locally, and 2) we can be sure the app is not missing any dependencies.

**Comment by alaindomissy** [comment]
" include the SingularityApp. file" ? I am not sure I understand
I still have the full Singularity recipres, but I renamed them
I renamed :
bioinformatics-fastqtools/SingularityApp.fastqtools → bioinformatics-fastqtools/Singularity.fastqtools
and
bioinformatics-fastqtools/SingularityApp.samtools → bioinformatics-fastqtools/Singularity.samtools
Should I revert to the SingularityApp.<tool>  filenames?
Is there a convention about SingularityApp.<tool> file names ?
Thanks

**Comment by vsoch** [comment]
exactly - my thinking is that there should be. The difference is that a Singularity Recipe file is for an entire/single recipe, and a SingularityApp is just the contents for one app. It would be confusing to see Singularity.app and then not have it build properly because it doesn't have full sections, etc.

**Comment by vsoch** [comment]
It looks like it's still having a little issue with doing the copy of files after the make, so I added a && to the next line, and am testing now - is that ok with you?

**Comment by alaindomissy** [comment]
How does this work ? It looks like the SingularityApp also has a global section:
'''
Bootstrap: docker
From: ubuntu:16.04
%post
   apt-get -y update
%environment
    export LC_ALL=C
'''
Do all the global sections from different  SingularityApp get merged when for instance picking up apps for the cart and downloading a full container recipe ?

Also by the way: I get ubuntu 14.04 , not 16.04 , when I download the generated recipe. Is this in purpose ?

Also: the included README.md had pre-2.4 building instructions:
'''
singularity create --size 2000 container.img
sudo singularity bootstrap container.img Singularity
...

**Comment by vsoch** [comment]
I don't have any functionality for the user to specify the base, it's just automatically added to be ubuntu 14.04.

The recipe isn't generated from the singularity files you provide - it's extracted from the `yaml` section in the file. You don't actually need to provide the recipe files - I was brainstorming that it might be useful for testing but to actually test I'm generating the container via the web interface (running locally) and then building it.

I saw the instructions are dated! I'm updating them with this PR. Thanks for the double catch!

**Comment by vsoch** [comment]
@alaindomissy I can't get the recipe that is generated to build correctly. Please run the server on your machine (bundle exec jekyll serve), then add the recipes to your recipe box, download, and generate.

**Comment by alaindomissy** [comment]
I d be happy to help but I don't know where to start. Is this related to gh-pages for static webistes on github ? I saw this : https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/  Should I read that ? Thanks

**Comment by vsoch** [comment]
yes that's a perfect start! I used to just cd to the base (where the _config.yml file is) and do `jekyll build` but it works much better to do `bundle exec jekyll build`. Then you basically open up to [localhost:4000/apps](localhost:4000/apps) and have the site on your local machine, all ready for testing! Let me know if you have questions along the way - glad to help out.

**Comment by alaindomissy** [comment]
OK this is what I did:
'''
sudo gem install bundler
bundle install
cd apps     # thisis where I git cloned the roeo locally
bundle exec jekyll build
bundle exec jekyll serve
''''
Now going to "http://127.0.0.1:4000/apps/" in my browser I can see a local version of the containers-ftw website! Yay! This is pretty awesome... but what did you want me to do with this now ?  
Oh I know... And I did that...
I used my local containers-ftw website to add the 2 bioinformatics app recipes to my recipe box,  generate and download.
I  changed one thing : I replaced From: ubuntu:14.04 with From: ubuntu:16.04
Then I ran: singularity build and was able to build 3 different simgs: one with both tools together and one with each of the tools seprataely.
All is working very well
I am not sure what was the problem you were having.... ? May be ubuntu 14.04 is a problem ?

**Comment by vsoch** [comment]
Awesome! The issue I was having wasn't particular to building, but checking that everything should be where it's expected. When I do

```
singularity run --app bioinformatics-fastqtools container.simg
```
I would expect to see a whole list of files (all of the ones you copied from the install). But I don't, I just see the one script:

```
fastqtools c.simg 
fastqtools v0.8
===============
the following commands are available:
fastqtools

Usage:
singularity run --app bioinformatics-fastqtools c.simg <command>
```
There should be many more commands on there, I think!

Samtools worked perfectly, it was just fastqtools that had this issue. Let me know if you can reproduce!

**Comment by alaindomissy** [comment]
I can reproduce the problem of the fastqtools executables not being copied, when I use ubuntu 1404 as the base. Now trying to figure out why...

**Comment by vsoch** [comment]
one thing I was thinking is with regard to the files section - it may be the case that if the base is used as a chroot, then whatever was there gets overridden. So I would try the build without the `%appfiles bioinformatics-fastqtools` section to see if it makes a difference. If so, we would want files added before build install, and should open an issue on the singularity board for that.

**Comment by alaindomissy** [comment]
I removed the "%appfiles bioinformatics-fastqtools"  section The executable s are still not copied.
When I build the exact same recipe , but with ubuntu 1604 as a base instead of 1404 , all works fine and there is no problem with having the "%appfiles" section
It seems to me that something is different in the way the appfiles sections is executed between ubuntu 1404 and ubuntu 1604: i tried "set -o xtrace" but that only shows me a trace in 1604.  Are we ending up using the same shell ? bash or sh ? and the same versions and shell options ?

I have a question: why still use ubuntu 1404? We now have 1604 as the most recent LTS. Ok I see here 1404 is still maintained until 2019.04. https://www.ubuntu.com/info/release-end-of-life. I'd still prefer to move on to 1604 

Remember also (it is unrelated but...) I also had several annoying troubles, when making vagrant boxes for the mac intall of singularity. I was initially trying based on ubunty 14.04 (supposedly "trusty") and later switched to 1604 which is the current long term release ad that was much better.

**Comment by vsoch** [comment]
Nope, not particularly any reason at all, just random choice! If you want to update the default to be 16.04, then that works for me :) If the build works after, that's the ideal outcome. When you get it working and are ready for another test from me, let me know!

**Comment by vsoch** [comment]
Here is where it's defined:

https://github.com/containers-ftw/apps/blob/ee6aa843c4f1b1f294ad167a7edd1d464c314c80/pages/generate.html#L32

My eventual plan is to have a choice of base OS based on the apps the user has selected, but haven't gotten that complicated yet... it's still sort of a "put together at your own risk" sort of deal.

**Comment by alaindomissy** [comment]
This PR is now completely replaced by PR # 22

**Comment by vsoch** [comment]
ok! Let me review #22

**Pull request closed without merging**
