### PR TITLE
replacing containers-ftw with sci-f to close #31

### LINKED ISSUE #31: Replace containers-ftw with sci-f in all URLs
There are a number of links pointing to https://containers-ftw.github.io which no longer work. I assume the main URL was changed at some point, and a few places were missed.

For example on the masthead of the GitHub repo:

Screen Shot 2020-04-10 at 09 15 51

And in the generated `index.json` file for the apps API (https://sci-f.github.io/apps/api/index.json):

Screen Shot 2020-04-10 at 09 17 39

Searching for "containers-ftw" in the organization shows following occurrences in code:

https://github.com/search?q=org%3Asci-f+%22containers-ftw%22&type=Code

I'm happy to help fix this, and creating this issue so I don't forget.

### PR DESCRIPTION
**Pull request by vsoch**
This is a PR to replace "containers-ftw" instances with sci-f, the issue was first opened in sci-f.github.io but the errors are largely here! This CI hasn't been run in a looong time so we will see how that goes... :)

This will close #31 

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
@julianpistorius would you care to take a quick look? It's not absolutely necessary - I think I replaced most of them. I did leave a few older URLS in asciinemas to preserve their original stage.

**Comment by julianpistorius** [comment]
Sure thing @vsoch. I had a quick look and spotted a couple of problems related to doubling up of the 'apps' path. This results in 404s. See below.

Screen Shot 2020-04-10 at 13 26 09

Screen Shot 2020-04-10 at 13 26 41

**Comment by vsoch** [comment]
Strange, it doesn't reproduce locally:

image

**Comment by vsoch** [comment]
I think it's because I'm using site.url instead of site.baseurl, I'll try that.

**Comment by vsoch** [comment]
Okay should be fixed, it was just the parsing of files had a manual "apps" in it that didn't need to be there.

**Pull request merged**
