### PR TITLE
change base to ubuntu:16.04

### PR DESCRIPTION
**Pull request by alaindomissy**

### CODE REVIEW

**Comment by alaindomissy** [comment]
There are more "14.04"  's lurking in the _site folder. Will these be updated automatically by Jekyll ?

**Comment by vsoch** [comment]
Yep, the site folder is not part of the repo, and is updated live when you make changes and the server is running. I think it probably uses fsnotify although I haven't looked into it.

**Comment by alaindomissy** [comment]
Did you want me to include this change in the other PR #19
instead of having it on its own in this one #21 ?

**Comment by vsoch** [comment]
Nope no need! Smaller PRs are much more optimal. Thanks @alaindomissy !

**Pull request merged**
