### PR TITLE
fastqtools main and sub commands usage

### PR DESCRIPTION
**Pull request by alaindomissy**
- this PR replaces completely PR #19, 
- better help and usage doc for fastqtools, 
- fully tested (with ubuntu 16.04 as the base) 
- local Jekyll was used to generate/download recipes:
  - for each separate tool 
  - as well as one recipe for the combination of both tools: fasqtools and samtools 
- those recipes were used to build squashfs images, 
- these simg's were tested and behaved as expected

### CODE REVIEW

**Comment by vsoch** [comment]
testing now!

**Comment by vsoch** [comment]
It works great! Just as stated and expected!! Super work on this @alaindomissy !

**Comment by vsoch** [comment]
Have you built these containers on Singularity Hub? It would be cool to let others try them out (without building haha).

**Comment by alaindomissy** [comment]
Thanks! I have not yet put them on shub, but I am going too (the 2 separate tools and a combination of both).
I am now thinking of changing my container building workflow to  take advantage of both containers-ftw and shub, (as pro grammatically as possible). Is there an API to interact with containers-ftw ?  wpuld like to submit a list of apps and automatically get the generated aggregated recipe, then post this in a github repo that is already monitored by shub and get an aggregated container built there. 
Have you considered starting as new channel for csif and containers-ftw in singularity slack ?

**Comment by vsoch** [comment]
containers-ftw is a statically generated site, so unfortunately no - however it does have a main manifest for all apps:

http://containers-ftw.org/apps/api/index.json

On the flip side, if you add an app to a container in singularity hub, you *do* get that stored with the container, although I haven't exposed it via any API endpoints. SHUB should primary be optimized for receiving / sending build hooks, and serving container manifests, so I'm hesitant to add "bonus" functions on top of that that might stress the application.

**Pull request merged**
